import React from "react";
import Footer from "../components/Footer";
import AddToCartBtn from "../components/ReusableComponents/AddToCartBtn";

export const fetchProducts = async () => {
  const res = await fetch("https://dummyjson.com/products/search?q=phone");
  const data = await res.json();
  const products = data.products;

  return products;
};

export const metadata = {
  title: "Productos | Essential Herbs ",
  description: "Generated by create next app",
};

async function ProductsPage() {
  const finalProducts = await fetchProducts();

  return (
    <div>
      <div
        className="mt-[96px]
    bg-[url(/images/productshero.jpg)] 
    bg-no-repeat bg-cover bg-center h-64  "
      >
        <h1 className="text-center text-white h-full flex items-center justify-center text-2xl ">
          Nuestros Productos
        </h1>
      </div>
      <div className="mt-20 w-full justify-center items-center flex flex-col gap-10 mb-20 lg:flex-row lg:w-[70vw] lg:mx-auto flex-wrap ">
        {finalProducts.map((item: any) => {
          return (
            <div className="justify-center items-center flex flex-col gap-5 bg-[#0E0E0E] p-5 rounded-md shadow-md hover:scale-105 transition-all duration-200 ease-in-out cursor-pointer min-w-[300px] w-[250px]  lg:w-4/12  lg:h-[400px]  ">
              <h2 className="text-white block text-xl">{item.title}</h2>

              <img
                src={item.thumbnail}
                alt={item.title}
                className="w-full h-[40%] aspect-square max-h-[200px] max-w-[300px]"
              />
              <div className="flex flex-col gap-5 max-w-[300px] mx-1 h-full justify-center items-center lg:gap-0 lg:overflow-hidden  ">
                <p className="text-white h-[60px]  flex items-center ">
                  {item.description.substring(0, 80)}
                </p>
                <div className="flex gap-4 text-white">
                  <p>Precio:</p>
                  <span className="text-white">${item.price}</span>
                </div>
                <AddToCartBtn />
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default ProductsPage;
